<div class="col-md-6 col-sm-12 col-xs-12 iproject-item">
          <div class="testimonials-block iproject-item">
            <div class="testimonials-photo"> <a href="[field:arcurl/]"><img src="[field:picname/]" alt="[field:title/]"/></a> </div>
            <div class="testimonials-text">
              <div class="testimonials-name">
                <h4 class="iproject-title"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h4>
              </div>
              <div class="testimonials-desc">
                <p>[field:description function="cn_substr(@me,200)"/]...</p>
              </div>
            </div>
          </div>
        </div>