<?php
$z[0]=Array("arcurl","",170,185);
$z[0][4]=array();
$z[1]=Array("picname","",197,213);
$z[1][4]=array();
$z[2]=Array("title","",220,234);
$z[2][4]=array();
$z[3]=Array("arcurl","",394,409);
$z[3][4]=array();
$z[4]=Array("title","",418,432);
$z[4][4]=array();
$z[5]=Array("title","",434,448);
$z[5][4]=array();
$z[6]=Array("description","",547,597);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,200)";

?>