<div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 iblog-item">
        <div class="blog-main">
          <div class="blog-images">
            <div class="post-thumbnail">
              <div class="single-item"></div>
              <div class="single-action"><span><a href="[field:arcurl/]"><i class="fa fa-eye"></i></a></span></div>
              <a href="[field:arcurl/]" class="thumb-link"><img src="[field:picname/]" alt="[field:title/]"/></a> </div>
          </div>
          <div class="blog-name"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></div>
          <div class="blog-desc">[field:description function="cn_substr(@me,200)"/]...<span class="inews-date">[[field:pubdate function="MyDate('Y-m-d',@me)"/]]</span></div>
        </div>
      </div>