<li class="cbp-item iport-item">
          <div class="cbp-item-wrapper">
            <div class="portfolio-dankovteam">
              <div class="portfolio-image"> <a href="[field:arcurl/]" class="thumb-link"><img src="[field:picname/]" alt="[field:title/]"/></a>
                
              </div>
              <h2 class="iport-title"><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
              
            </div>
          </div>
        </li>